language: c++
# Theoretically, this would allow us to clone subdmoules in parallel, which is quite slow.
# However, travis's git submodule doesn't understand --jobs
#git:
#  submodules: false
#before_install:
#  - git submodule update --init --recursive --jobs=4
env:
  global:
    - MAKEFLAGS=-j3
script:
  # We need --verbose or Travis thinks our build has stalled.
  - install/build_release.sh --verbose --skip_psol
sudo: required
compiler:
  - gcc
notifications:
  email:
    - cheesy@google.com
    - jefftk@google.com
    - morlovich@google.com
    - jmarantz@google.com
    - huibao@google.com
